### PR TITLE
fix: handle undefined in arguments

### LINKED ISSUE #148: Failed hash calculation while log errors when using default Logger in NestJS v9.3.0 and later
See https://github.com/nestjs/nest/pull/10531 for more details

### PR DESCRIPTION
**Pull request by KillWolfVlad**
Fix #148

### CODE REVIEW

File: src/providers/pinoLoggerOptionsBuilder.ts [hunk 1]
```diff
@@ -115,7 +115,10 @@ export class PinoLoggerOptionsBuilder {
       function getMessageFromError(args) {
         const [o, ...n] = args as [Record<string, unknown>, ...unknown[]];
```
Comment (nmorgunov) [inline src/providers/pinoLoggerOptionsBuilder.ts]: what is o? What is n? 
go full naming

File: src/__tests__/pinoLoggerOptionsBuilder.spec.ts [hunk 2]
```diff
@@ -86,6 +86,28 @@ describe("PinoLoggerOptionsBuilder", () => {
     expect(JSON.parse(stdout.output)).toMatchSnapshot();
   });
 
+  it("must log error with extra undefined argument", () => {
+    const error = new Error("some error");
+    error.stack = "Error: some error";
+
+    const extraArguments = [undefined];
```
Comment (nmorgunov) [inline src/__tests__/pinoLoggerOptionsBuilder.spec.ts:96]: What happen if  extraArguments =['arg', undefined] ?

**Review by nmorgunov — CHANGES_REQUESTED** [review]

File: src/__tests__/pinoLoggerOptionsBuilder.spec.ts (hunk 2 above)
Comment (wisedog706) [reply src/__tests__/pinoLoggerOptionsBuilder.spec.ts:96]: in this case, hash of 'arg' must be calculated as `message.msgTemplateHash`

nest upper than 9.3.0 insert `undefined` as first additional param in case, when we log error object without additional parameters in log.error(). 
And if we use pino in nest with config from this factory, `calculateHash` function throw error when try to calculate hash for msgTemplateHash(which is be undefined)

File: src/providers/pinoLoggerOptionsBuilder.ts (hunk 1 above)
Comment (wisedog706) [reply src/providers/pinoLoggerOptionsBuilder.ts]: `o` is message for log.
`n` is additional params from `logger` method

renamed to these names

**Review by nmorgunov — APPROVED** [review]
